Run unit tests from scripts
Signed-off-by: Charlie Truong <chtruong@nvidia.com>

diff --git a/.github/workflows/cicd-main.yml b/.github/workflows/cicd-main.yml
--- a/.github/workflows/cicd-main.yml
+++ b/.github/workflows/cicd-main.yml
@@ -174,19 +174,19 @@ jobs:
   #       cd /opt/nemo-rl/docs
   #       uv run --no-sync sphinx-build -b doctest . _build/doctest
 
-  unit-tests-generation:
-    name: Unit Tests
-    needs: [build-container, pre-flight]
-    uses: ./.github/workflows/_run_test.yml
-    if: ${{ contains('L0 L1 L2', needs.pre-flight.outputs.test_level) }}
-    secrets:
-      HF_TOKEN: ${{ secrets.HF_TOKEN }}
-    with:
-      RUNNER: self-hosted-azure
-      TIMEOUT: 180
-      TEST_SCRIPT: |
-        cd /opt/nemo-rl
-        uv run --no-sync bash -x ./tests/run_unit.sh unit/models/policy/ --cov=nemo_rl --cov-report=term --cov-report=json
+  # unit-tests-generation:
+  #   name: Unit Tests
+  #   needs: [build-container, pre-flight]
+  #   uses: ./.github/workflows/_run_test.yml
+  #   if: ${{ contains('L0 L1 L2', needs.pre-flight.outputs.test_level) }}
+  #   secrets:
+  #     HF_TOKEN: ${{ secrets.HF_TOKEN }}
+  #   with:
+  #     RUNNER: self-hosted-azure
+  #     TIMEOUT: 180
+  #     TEST_SCRIPT: |
+  #       cd /opt/nemo-rl
+  #       uv run --no-sync bash -x ./tests/run_unit.sh unit/models/policy/ --cov=nemo_rl --cov-report=term --cov-report=json
 
   # functional-tests:
   #   name: Functional Tests
@@ -207,6 +207,102 @@ jobs:
   #       time uv run --no-sync bash ./tests/functional/dpo.sh
   #       time uv run --no-sync bash ./tests/functional/eval.sh
   #       time uv run --no-sync bash ./tests/functional/test_mcore_extra_installed_correctly.sh
+
+  cicd-unit-tests:
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - script: L0_Unit_Tests_Generation
+            runner: self-hosted-azure
+          - script: L0_Unit_Tests_Policy
+            runner: self-hosted-azure
+          - script: L0_Unit_Tests_Other
+            runner: self-hosted-azure
+    needs: [pre-flight, build-container]
+    if: ${{ contains('L0 L1 L2', needs.pre-flight.outputs.test_level) }}
+    runs-on: ${{ matrix.runner }}
+    name: ${{ matrix.script }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: main
+        uses: ./.github/actions/test-template
+        with:
+          runner: ${{ runner.name }}
+          script: ${{ matrix.script }}
+          timeout: ${{ matrix.timeout || 10 }}
+          is_unit_test: "true"
+          cpu-only: ${{ matrix.cpu-only || false }}
+
+  # cicd-e2e-tests:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - script: L2_Functional_Tests_GPU
+  #           runner: linux-amd64-gpu-rtxa6000-latest-2-nemo
+  #           timeout: 30
+  #   needs: [cicd-unit-tests]
+  #   runs-on: ${{ matrix.runner }}
+  #   name: ${{ matrix.is_optional && 'PLEASEFIXME_' || '' }}${{ matrix.script }}
+  #   environment: nemo-ci
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: main
+  #       uses: ./.github/actions/test-template
+  #       with:
+  #         runner: ${{ runner.name }}
+  #         script: ${{ matrix.script }}
+  #         timeout: ${{ matrix.timeout || 10 }}
+
+  Nemo_CICD_Test:
+    needs:
+      - build-container
+      - cicd-unit-tests
+    if: always()
+    runs-on: ubuntu-latest
+    permissions: write-all
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Get workflow result
+        id: result
+        env:
+          GH_TOKEN: ${{ github.token }}
+          RUN_ID: ${{ github.run_id }}
+        run: |
+          # Get workflow run details and check job conclusions
+          LATEST_ATTEMPT=$(gh run view $RUN_ID --json jobs -q '[.jobs[] | select(.conclusion != null) | .conclusion] | last')
+          NUM_FAILED=$(gh run view $RUN_ID --json jobs -q '[.jobs[] | select(.conclusion == "failure") | .name] | length')
+          NUM_CANCELLED=$(gh run view $RUN_ID --json jobs -q '[.jobs[] | select(.conclusion == "cancelled") | .name] | length')
+
+          if [[ $NUM_FAILED -eq 0 && $NUM_CANCELLED -eq 0 ]]; then
+            RESULT="success"
+          elif [[ $NUM_CANCELLED -gt 0 ]]; then
+            RESULT="cancelled"
+          else
+            RESULT="failure"
+          fi
+
+          # Output the final status
+          echo "code=$RESULT" | tee -a $GITHUB_OUTPUT
+
+      - name: Checkout for GH CLI
+        uses: actions/checkout@v4
+
+      - name: Exit
+        if: ${{ always() }}
+        env:
+          RESULT: ${{ steps.result.outputs.code }}
+        run: |
+          if [ $RESULT == "success" ]; then
+            exit 0
+          else
+            exit 1
+          fi
 
   # coverage:
   #   name: Upload coverage to Codecov
@@ -232,52 +328,52 @@ jobs:
   #         verbose: true
   #         override_branch: ${{ github.event_name == 'merge_group' && 'main' || '' }}
 
-  CI_QA_Gate:
-    name: CI quality check
-    if: always()
-    runs-on: ubuntu-latest
-    needs:
-      - pre-flight
-      - lint-check
-      - sphinx-build
-      # - doc-tests
-      - unit-tests-generation
-      # - functional-tests
-    steps:
-      - name: main
-        env:
-          JOB_RESULTS: ${{ toJSON(needs) }}
-          # Job is considered successful if nothing was run, or if all jobs were successful (the tests run even if only docs were run b/c doctests are selected)
-          ALL_SUCCESS: >-
-            ${{
-              needs.lint-check.result == 'success' &&
-              (
-                needs.pre-flight.outputs.test_level == 'none' ||
-                (
-                  needs.pre-flight.outputs.test_level != 'none' &&
-                  needs.sphinx-build.result == 'success' &&
-                  (
-                    (
-                      (needs.unit-tests-generation.result == 'skipped' || needs.unit-tests-generation.result == 'success')
-                    )
-                  ) &&
-                  (needs.mypy-check.result == 'success' || true)
-                )
-              )
-            }}
-          CI_SKIP: ${{ github.event.label.name == 'Skip CICD' }}
-          TEST_LEVEL: ${{ needs.pre-flight.outputs.test_level }}
-        run: |
-          SUMMARY=$(echo $JOB_RESULTS | jq 'to_entries[] | .key + ": " + .value.result' | tr -d '"')
-          echo '🤖: CICD Result for test level: ${{ needs.pre-flight.outputs.test_level }}' >> $GITHUB_STEP_SUMMARY
-          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+  # CI_QA_Gate:
+  #   name: CI quality check
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - pre-flight
+  #     - lint-check
+  #     - sphinx-build
+  #     # - doc-tests
+  #     - unit-tests-generation
+  #     # - functional-tests
+  #   steps:
+  #     - name: main
+  #       env:
+  #         JOB_RESULTS: ${{ toJSON(needs) }}
+  #         # Job is considered successful if nothing was run, or if all jobs were successful (the tests run even if only docs were run b/c doctests are selected)
+  #         ALL_SUCCESS: >-
+  #           ${{
+  #             needs.lint-check.result == 'success' &&
+  #             (
+  #               needs.pre-flight.outputs.test_level == 'none' ||
+  #               (
+  #                 needs.pre-flight.outputs.test_level != 'none' &&
+  #                 needs.sphinx-build.result == 'success' &&
+  #                 (
+  #                   (
+  #                     (needs.unit-tests-generation.result == 'skipped' || needs.unit-tests-generation.result == 'success')
+  #                   )
+  #                 ) &&
+  #                 (needs.mypy-check.result == 'success' || true)
+  #               )
+  #             )
+  #           }}
+  #         CI_SKIP: ${{ github.event.label.name == 'Skip CICD' }}
+  #         TEST_LEVEL: ${{ needs.pre-flight.outputs.test_level }}
+  #       run: |
+  #         SUMMARY=$(echo $JOB_RESULTS | jq 'to_entries[] | .key + ": " + .value.result' | tr -d '"')
+  #         echo '🤖: CICD Result for test level: ${{ needs.pre-flight.outputs.test_level }}' >> $GITHUB_STEP_SUMMARY
+  #         echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
 
-          if [[ "$TEST_LEVEL" == "none" ]]; then
-            echo "No tests were run, passing gate" >> $GITHUB_STEP_SUMMARY
-            exit 0
-          fi
+  #         if [[ "$TEST_LEVEL" == "none" ]]; then
+  #           echo "No tests were run, passing gate" >> $GITHUB_STEP_SUMMARY
+  #           exit 0
+  #         fi
 
-          test "$ALL_SUCCESS" = "true" || test "$CI_SKIP" = "true"
+  #         test "$ALL_SUCCESS" = "true" || test "$CI_SKIP" = "true"
 
   DCO_merge_group:
     name: DCO
